spring:
 cloud:
   gateway:
     routes:
       - id: blog-service
         uri: lb://BLOG-SERVICE
         predicates:
           - Path=/api/posts/**, /v3/api-docs/blog
         filters:
           - AuthenticationFilter

       - id: authentication-service
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**, /v3/api-docs/authentication

 application:
   name: api-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true
